config/routes.rb
Rails.application.routes.draw do
  resources :reviews, except: [:show, :index]
  devise_for :users
  resources :sneakers do
      resources :reviews, except: [:show, :index]
    end
  get 'pages/about'

  get 'pages/contact'
  
  root 'sneakers#index'

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :sneaker
   validates :rating, :comment, presence: true
    validates :rating, numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1,
      less_than_or_equal_to: 5,
      message: "can only be a whole number between 1 and 5"
    }
  end

app/models/sneaker.rb
class Sneaker < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  
  
  has_many :reviews
    validates :brand, :name, :style, :buy, :image, presence: true
    validates :buy, format: { with: /\Ahttps?:\/\/.*\z/,
      message: "must start with http:// or https://" }
  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews, dependent: :destroy     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :first_name
      devise_parameter_sanitizer.for(:sign_up) << :last_name
      devise_parameter_sanitizer.for(:account_update) << :first_name
      devise_parameter_sanitizer.for(:account_update) << :last_name

    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
 
  before_action :set_sneaker
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]
  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.sneaker_id = @sneaker.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to root_path, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to sneaker_path(@sneaker), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to sneakers_path(@sneakers), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_sneaker
      @sneaker = Sneaker.find(params[:sneaker_id])
    end  
  
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
    
    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this review belongs to someone else"
      end
    end
    
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  before_action :set_sneaker, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search, :index, :show]
  before_action :check_user, except: [:search, :index, :show]



  # GET /sneakers
  # GET /sneakers.json
  def index
    @sneakers = Sneaker.all
  end

  # GET /sneakers/1
  # GET /sneakers/1.json
  def show
    @reviews = Review.where(sneaker_id: @sneaker.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /sneakers/new
  def new
    @sneaker = Sneaker.new
  end

  # GET /sneakers/1/edit
  def edit
  end

  # POST /sneakers
  # POST /sneakers.json
  def create
    @sneaker = Sneaker.new(sneaker_params)

    respond_to do |format|
      if @sneaker.save
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully created.' }
        format.json { render :show, status: :created, location: @sneaker }
      else
        format.html { render :new }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sneakers/1
  # PATCH/PUT /sneakers/1.json
  def update
    respond_to do |format|
      if @sneaker.update(sneaker_params)
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @sneaker }
      else
        format.html { render :edit }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sneakers/1
  # DELETE /sneakers/1.json
  def destroy
    @sneaker.destroy
    respond_to do |format|
      format.html { redirect_to sneakers_url, notice: 'Sneaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sneaker
      @sneaker = Sneaker.find(params[:id])
    end



    def check_user
      unless current_user.admin?
          redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sneaker_params
      params.require(:sneaker).permit(:brand, :name, :style, :buy, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/views/layouts/_bootstrap.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link href='https://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	  <%= link_to "SneakerStats.com", root_path, class: "navbar-brand" %>
    </div>
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  <ul class="nav navbar-nav">
	    <li><%= link_to "About", pages_about_path %></li>
	    <li><%= link_to "Contact", pages_contact_path %></li>
	  </ul>
      
	    <ul class="nav navbar-nav navbar-right">
		<a href="https://instagram.com/sneakerstats_com/" target="parent"><img src="https://s3.amazonaws.com/sneakerstats/icons/Instagram_Icon_Large.png"></a>
		<a href="https://www.facebook.com/sneakerstats" target="parent"><img src="https://s3.amazonaws.com/sneakerstats/icons/FB-f-Logo__blue_50.png"></a>
		<a href="https://twitter.com/sneakerstatscom" target="parent">	<img src="https://s3.amazonaws.com/sneakerstats/icons/TwitterLogo_%2355acee.png"></a>
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sneakerstats</title>
  <%= render 'layouts/bootstrap' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container-fluid">
	
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to SneakerStats</h1>
<h3>We all love our kicks, but how do they perform IRL ?
	<br><br>
	Have your say, share the love, or hate. Do they stand up to the everyday grind, or are they so sweet you just have to keep em on ice ?<br><br>
	Something on your bucket list?<br><br> Let us know ! </h3><br><br>
	Made in PA
	
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-66931422-1', 'auto');
	  ga('send', 'pageview');

	</script>

app/views/pages/contact.html.erb
<h1>Like the site, or hate it? Let us know! </h1><br> Want to get involved? We need moderators. Review some kicks and reach out.<br><br>
<p><iframe src="https://docs.google.com/forms/d/1W6VicmAZeFTrfiQmJV3ARmQJ91j6segwE_wbDlsbVl0/viewform?embedded=true" width="720" height="695" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe></p>
<br><br>
Made in PA

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66931422-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/reviews/_form.html.erb
<%= form_for([@sneaker, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="star-rating"></div>
  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.submit  class: "btn btn-primary"%>
  </div>
<% end %>
<script>
  $('#star-rating').raty({
    path: 'https://s3.amazonaws.com/yelpdemo77/Stars',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>
<%= link_to 'Back', sneaker_path(@sneaker) %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>
<%= link_to 'Back', sneaker_path(@sneaker) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/sneakers/_form.html.erb
<%= form_for(@sneaker, :html => { multipart: true }) do |f| %>
  <% if @sneaker.errors.any? %>
  <div id="error_explanation" class= "alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4><%= pluralize(@sneaker.errors.count, "error") %> prohibited this sneaker from being saved:</h4>

      <ul>
      <% @sneaker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :brand %><br>
    <%= f.text_field :brand, class: "form-control", placeholder: "Nike" %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Nike"  %>
  </div>
  <div class="form-group">
    <%= f.label :style %><br>
    <%= f.text_field :style, class: "form-control", placeholder: "Nike"  %>
  </div>
  <div class="form-group">
    <%= f.label :buy %><br>
    <%= f.text_field :buy, class: "form-control", placeholder: "Nike"  %>
  </div>
  <div class="form-group"> 
    <%= f.label :image %><br> 
    <%= f.file_field :image, class: "form-control" %> 
   </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sneakers/edit.html.erb
<h1>Editing Sneaker</h1>

<%= render 'form' %>

<%= link_to 'Show', @sneaker, class: "btn btn-link" %> |
<%= link_to 'Back', sneakers_path, class: "btn btn-link" %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66931422-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/sneakers/index.html.erb
<div class ="jumbotron">
  <h2>Tell us about your latest kicks</h2>
  <h3>Share your experiences with the styles you love.
  <br>Leave reviews and ratings for your fellow sneakerheads.</h3>
</div>


	<form id="live-search" role="search" method="post">
	<input type="text" class="form-control" placeholder="Start Typing to Filter Results"/>
	</div>
	</form>
<div class="container-fluid">
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Brand</th>
      <th>Name</th>
      <th>Style</th>
      <th>Buy</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody class = "searchable">
    <% @sneakers.each do |sneaker| %>
      <tr>
        <td><%= sneaker.brand%></td>
        <td><%= link_to sneaker.name, sneaker %></td>
        <td><%= sneaker.style %></td>
        <td><%= link_to sneaker.buy, sneaker.buy %></td> 
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_sneaker_path(sneaker) %></td>
          <td><%= link_to 'Destroy', sneaker, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Sneaker', new_sneaker_path, class: "btn btn-link" %>
<% end %>
</div>
<div class="container-fluid">
Made in PA
</div>
<script>
$('input.form-control').on('keyup', function() {
    var rex = new RegExp($(this).val(), 'i');
    $('.searchable tr').hide();
    $('.searchable tr').filter(function() {
    return rex.test($(this).text());
    }).show();
    });
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66931422-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/sneakers/new.html.erb
<h1>New Sneaker</h1>

<%= render 'form' %>

<%= link_to 'Back', sneakers_path, class: "btn btn-link" %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66931422-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/sneakers/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Brand</th>
      <th>Name</th>
      <th>Style</th>
      <th>Buy</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @sneakers.each do |sneaker| %>
      <tr>
        <td><%= sneaker.brand%></td>
        <td><%= link_to sneaker.name %></td>
        <td><%= sneaker.style %></td>
        <td><%= link_to sneaker.buy, sneaker.buy %></td> 
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_sneaker_path(sneaker) %></td>
          <td><%= link_to 'Destroy', sneaker, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sneakers/show.html.erb
<div class="row">
  <div class="col-md-3">
<%= image_tag @sneaker.image_url %>

<h2>
  <%= @sneaker.name %>
</h2>
<div class="star-rating" data-score= <%= @avg_rating %> ></div>
<p><%= "#{@reviews.length} reviews" %></p>
 
<p>
  <br>	
  <strong>Brand:</strong>
  <%= @sneaker.brand %>
</p>

<p>
  <strong>Style:</strong>
  <%= @sneaker.style %>
</p>

<p>
  <strong>Buy:</strong>
  <%= @sneaker.buy %>
</p>
<%= link_to "Review", new_sneaker_review_path(@sneaker), class: "btn btn-primary" %>
</div>
  <div class="col-md-9">
    <% if @reviews.blank? %>
      <h3>Like this kick? be the first to comment...</h3>
    <% else %>
	<table class="table">
		<thead>
	      <tr>
	        <th class="col-md-3"></th>
	        <th class="col-md-9"></th>
	      </tr>
	    </thead>	
	  <tbody>
		<% @reviews.each do |review| %>
		<tr>
		<td>
           <h4>
             <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
           </h4>
           <p><%= review.created_at.strftime("%-m/%-d/%-y") %></p>
         </td>

         <td>
			<div class="star-rating" data-score= <%= review.rating %> ></div>
			<p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
			<% if user_signed_in? %>
			  <% if (review.user == current_user) || (current_user.admin?) %>
			    <%= link_to "Edit", edit_sneaker_review_path(@sneaker, review) %>
			    <%= link_to "Delete", sneaker_review_path(@sneaker, review), method: :delete %>
			  <% end %>
			<% end %>	
		</tr>	
		 <% end %>
	  </tbody>
	</table>
    <% end %>
  </div>
</div>


<%= link_to 'Edit', edit_sneaker_path(@sneaker),class: "btn btn-link" %> |
<%= link_to 'Back', sneakers_path,class: "btn btn-link" %>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/sneakerstats/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66931422-1', 'auto');
  ga('send', 'pageview');

</script>